
gpeek.spawnmenu.daddonbrowser.tooltip=Prehliadanie vnútorných mechanizmov

gpeek.extensions.error.message=Typ súboru nie je momentálne podporovaný.

gpeek.extensions.lua.empty=Tento súbor je prázdny
gpeek.extensions.lua.copy=Kopírovať obsah súboru

gpeek.extensions.mdl.animations.placeholder=vybrať animáciu...
gpeek.extensions.mdl.skin=Skin
gpeek.extensions.mdl.invert=Invertovať pozadie

gpeek.extensions.pcf.message=Na zobrazenie tohto súboru potrebujete 'Particle Effects+' (3684885115).
gpeek.extensions.pcf.workshop=Zobraziť vo Workshop

gpeek.extensions.ttf.fontscale=Veľkosť písma
gpeek.extensions.ttf.error=Písmo sa nepodarilo načítať.
gpeek.extensions.ttf.copy=Kopírovať názov písma

gpeek.extensions.vmt.texture=Textúra
gpeek.extensions.vmt.scale=Mierka
gpeek.extensions.vmt.invert=Invertovať pozadie
gpeek.extensions.vmt.material=Materiál

gpeek.extensions.wav.stop=Zastaviť
gpeek.settings=Nastavenia gPeek
gpeek.settings.multiaddon=Prehliadanie viacerých doplnkov
gpeek.settings.multiaddon.help=\nUmožňuje prehliadanie viacerých doplnkov súčasne. Otvorenie veľkého množstva doplnkov môže spôsobiť oneskorenie.
gpeek.settings.batchsize=Veľkosť dávky súborov
gpeek.settings.batchsize.help=\nPočet súborov spracovaných za dávku pri prehliadaní doplnku.
gpeek.settings.batchdelay=Oneskorenie dávky súborov
gpeek.settings.batchdelay.help=\nČas medzi jednotlivými dávkami súborov pri prehliadaní doplnku.
gpeek.settings.blacklist=Čierna listina súborov