
gpeek.spawnmenu.daddonbrowser.tooltip=Prehliadanie vnútorných mechanizmov

gpeek.extensions.error.message=Typ súboru nie je momentálne podporovaný.

gpeek.extensions.lua.empty=Tento súbor je prázdny
gpeek.extensions.lua.copy=Kopírovať obsah súboru

gpeek.extensions.mdl.animations.placeholder=vybrať animáciu...
gpeek.extensions.mdl.skin=Skin
gpeek.extensions.mdl.invert=Invertovať pozadie

gpeek.extensions.pcf.message=Na zobrazenie tohto súboru potrebujete 'Particle Effects+' (3684885115).
gpeek.extensions.pcf.workshop=Zobraziť vo Workshop

gpeek.extensions.ttf.fontscale=Veľkosť písma
gpeek.extensions.ttf.error=Písmo sa nepodarilo načítať.
gpeek.extensions.ttf.copy=Kopírovať názov písma

gpeek.extensions.vmt.texture=Textúra
gpeek.extensions.vmt.scale=Mierka
gpeek.extensions.vmt.invert=Invertovať pozadie
gpeek.extensions.vmt.material=Materiál

gpeek.extensions.wav.stop=Zastaviť