
gpeek.spawnmenu.daddonbrowser.tooltip=Bläddra i de inre mekanismerna

gpeek.extensions.error.message=Filtypen stöds inte för närvarande.

gpeek.extensions.lua.empty=Den här filen är tom
gpeek.extensions.lua.copy=Kopiera filinnehåll

gpeek.extensions.mdl.animations.placeholder=välj animation...
gpeek.extensions.mdl.skin=Skin
gpeek.extensions.mdl.invert=Invertera bakgrund

gpeek.extensions.pcf.message=Du behöver 'Particle Effects+' (3684885115) för att visa den här filen.
gpeek.extensions.pcf.workshop=Se i Workshop

gpeek.extensions.ttf.fontscale=Teckenstorlek
gpeek.extensions.ttf.error=Det gick inte att läsa in teckensnittet.
gpeek.extensions.ttf.copy=Kopiera teckensnittsnamn

gpeek.extensions.vmt.texture=Textur
gpeek.extensions.vmt.scale=Skala
gpeek.extensions.vmt.invert=Invertera bakgrund
gpeek.extensions.vmt.material=Material

gpeek.extensions.wav.stop=Stoppa