
gpeek.spawnmenu.daddonbrowser.tooltip=Procházení vnitřních mechanismů

gpeek.extensions.error.message=Tento typ souboru není aktuálně podporován.

gpeek.extensions.lua.empty=Tento soubor je prázdný
gpeek.extensions.lua.copy=Kopírovat obsah souboru

gpeek.extensions.mdl.animations.placeholder=vyberte animaci...
gpeek.extensions.mdl.skin=Skin
gpeek.extensions.mdl.invert=Invertovat pozadí

gpeek.extensions.pcf.message=Pro zobrazení tohoto souboru potřebujete 'Particle Effects+' (3684885115).
gpeek.extensions.pcf.workshop=Zobrazit ve Workshop

gpeek.extensions.ttf.fontscale=Velikost písma
gpeek.extensions.ttf.error=Písmo nelze načíst.
gpeek.extensions.ttf.copy=Kopírovat název písma

gpeek.extensions.vmt.texture=Textura
gpeek.extensions.vmt.scale=Měřítko
gpeek.extensions.vmt.invert=Invertovat pozadí
gpeek.extensions.vmt.material=Materiál

gpeek.extensions.wav.stop=Zastavit
gpeek.settings=Nastavení gPeek
gpeek.settings.multiaddon=Procházení více doplňků
gpeek.settings.multiaddon.help=\nUmožňuje procházet více doplňků současně. Otevření mnoha doplňků může způsobit zpomalení.
gpeek.settings.batchsize=Velikost dávky souborů
gpeek.settings.batchsize.help=\nPočet souborů zpracovávaných v dávce při procházení doplňku.
gpeek.settings.batchdelay=Zpoždění dávky souborů
gpeek.settings.batchdelay.help=\nČas mezi každou dávkou souborů při procházení doplňku.
gpeek.settings.blacklist=Černá listina souborů