
gpeek.spawnmenu.daddonbrowser.tooltip=Sisemiste mehhanismide sirvimine

gpeek.extensions.error.message=Seda failitüüpi ei toetata praegu.

gpeek.extensions.lua.empty=See fail on tühi
gpeek.extensions.lua.copy=Kopeeri faili sisu

gpeek.extensions.mdl.animations.placeholder=vali animatsioon...
gpeek.extensions.mdl.skin=Nahk
gpeek.extensions.mdl.invert=Pööra taust ümber

gpeek.extensions.pcf.message=Selle faili vaatamiseks on vaja 'Particle Effects+' (3684885115).
gpeek.extensions.pcf.workshop=Vaata Workshops

gpeek.extensions.ttf.fontscale=Fondi suurus
gpeek.extensions.ttf.error=Fonti ei saanud laadida.
gpeek.extensions.ttf.copy=Kopeeri fondi nimi

gpeek.extensions.vmt.texture=Tekstuur
gpeek.extensions.vmt.scale=Skaala
gpeek.extensions.vmt.invert=Pööra taust ümber
gpeek.extensions.vmt.material=Materjal

gpeek.extensions.wav.stop=Peata
gpeek.settings=gPeek seaded
gpeek.settings.multiaddon=Mitme lisandmooduli sirvimine
gpeek.settings.multiaddon.help=\nLubab mitme lisandmooduli samaaegset sirvimist. Paljude lisandmoodulite avamine võib põhjustada mahajäämust.
gpeek.settings.batchsize=Failide partii suurus
gpeek.settings.batchsize.help=\nFailide arv, mida töödeldakse partii kohta lisandmooduli sirvimise ajal.
gpeek.settings.batchdelay=Failide partii viivitus
gpeek.settings.batchdelay.help=\nAeg iga failide partii vahel lisandmooduli sirvimise ajal.
gpeek.settings.blacklist=Failide must nimekiri