
gpeek.spawnmenu.daddonbrowser.tooltip=Bla gjennom de indre mekanismene

gpeek.extensions.error.message=Filtypen støttes ikke for øyeblikket.

gpeek.extensions.lua.empty=Denne filen er tom
gpeek.extensions.lua.copy=Kopier filinnhold

gpeek.extensions.mdl.animations.placeholder=velg animasjon...
gpeek.extensions.mdl.skin=Skin
gpeek.extensions.mdl.invert=Inverter bakgrunn

gpeek.extensions.pcf.message=Du trenger 'Particle Effects+' (3684885115) for å se denne filen.
gpeek.extensions.pcf.workshop=Se i Workshop

gpeek.extensions.ttf.fontscale=Skriftstørrelse
gpeek.extensions.ttf.error=Kunne ikke laste inn skrifttype.
gpeek.extensions.ttf.copy=Kopier skrifttypens navn

gpeek.extensions.vmt.texture=Tekstur
gpeek.extensions.vmt.scale=Skala
gpeek.extensions.vmt.invert=Inverter bakgrunn
gpeek.extensions.vmt.material=Materiale

gpeek.extensions.wav.stop=Stopp
gpeek.settings=gPeek innstillinger
gpeek.settings.multiaddon=Bla gjennom flere tillegg
gpeek.settings.multiaddon.help=\nTillat å bla gjennom flere tillegg samtidig. Å åpne mange tillegg kan forårsake etterslep.
gpeek.settings.batchsize=Filbatchstørrelse
gpeek.settings.batchsize.help=\nAntall filer som behandles per batch ved gjennomgang av et tillegg.
gpeek.settings.batchdelay=Filbatchforsinkelse
gpeek.settings.batchdelay.help=\nTid mellom hver filbatch ved gjennomgang av et tillegg.
gpeek.settings.blacklist=Filsvarteliste