
gpeek.spawnmenu.daddonbrowser.tooltip=גלישה במנגנונים הפנימיים

gpeek.extensions.error.message=סוג הקובץ אינו נתמך כרגע.

gpeek.extensions.lua.empty=קובץ זה ריק
gpeek.extensions.lua.copy=העתק תוכן קובץ

gpeek.extensions.mdl.animations.placeholder=בחר אנימציה...
gpeek.extensions.mdl.skin=עור
gpeek.extensions.mdl.invert=הפוך רקע

gpeek.extensions.pcf.message=אתה צריך את 'Particle Effects+' (3684885115) כדי לצפות בקובץ זה.
gpeek.extensions.pcf.workshop=ראה ב-Workshop

gpeek.extensions.ttf.fontscale=גודל גופן
gpeek.extensions.ttf.error=לא ניתן לטעון גופן.
gpeek.extensions.ttf.copy=העתק שם גופן

gpeek.extensions.vmt.texture=מרקם
gpeek.extensions.vmt.scale=קנה מידה
gpeek.extensions.vmt.invert=הפוך רקע
gpeek.extensions.vmt.material=חומר

gpeek.extensions.wav.stop=עצור