
gpeek.spawnmenu.daddonbrowser.tooltip=גלישה במנגנונים הפנימיים

gpeek.extensions.error.message=סוג הקובץ אינו נתמך כרגע.

gpeek.extensions.lua.empty=קובץ זה ריק
gpeek.extensions.lua.copy=העתק תוכן קובץ

gpeek.extensions.mdl.animations.placeholder=בחר אנימציה...
gpeek.extensions.mdl.skin=עור
gpeek.extensions.mdl.invert=הפוך רקע

gpeek.extensions.pcf.message=אתה צריך את 'Particle Effects+' (3684885115) כדי לצפות בקובץ זה.
gpeek.extensions.pcf.workshop=ראה ב-Workshop

gpeek.extensions.ttf.fontscale=גודל גופן
gpeek.extensions.ttf.error=לא ניתן לטעון גופן.
gpeek.extensions.ttf.copy=העתק שם גופן

gpeek.extensions.vmt.texture=מרקם
gpeek.extensions.vmt.scale=קנה מידה
gpeek.extensions.vmt.invert=הפוך רקע
gpeek.extensions.vmt.material=חומר

gpeek.extensions.wav.stop=עצור
gpeek.settings=הגדרות gPeek
gpeek.settings.multiaddon=עיון בתוספים מרובים
gpeek.settings.multiaddon.help=\nאפשר עיון במספר תוספים בו-זמנית. פתיחת תוספים רבים עלולה לגרום לפיגור.
gpeek.settings.batchsize=גודל אצווה של קבצים
gpeek.settings.batchsize.help=\nמספר הקבצים לעיבוד לאצווה בעת עיון בתוסף.
gpeek.settings.batchdelay=עיכוב אצווה של קבצים
gpeek.settings.batchdelay.help=\nזמן בין כל אצווה של קבצים בעת עיון בתוסף.
gpeek.settings.blacklist=רשימה שחורה של קבצים