
gpeek.spawnmenu.daddonbrowser.tooltip=内部の仕組みを閲覧中

gpeek.extensions.error.message=このファイル形式は現在サポートされていません。

gpeek.extensions.lua.empty=このファイルは空です
gpeek.extensions.lua.copy=ファイルの内容をコピー

gpeek.extensions.mdl.animations.placeholder=アニメーションを選択...
gpeek.extensions.mdl.skin=スキン
gpeek.extensions.mdl.invert=背景を反転

gpeek.extensions.pcf.message=このファイルを表示するには 'Particle Effects+' (3684885115) が必要です。
gpeek.extensions.pcf.workshop=Workshopで見る

gpeek.extensions.ttf.fontscale=フォントサイズ
gpeek.extensions.ttf.error=フォントを読み込めませんでした。
gpeek.extensions.ttf.copy=フォント名をコピー

gpeek.extensions.vmt.texture=テクスチャ
gpeek.extensions.vmt.scale=スケール
gpeek.extensions.vmt.invert=背景を反転
gpeek.extensions.vmt.material=マテリアル

gpeek.extensions.wav.stop=停止