
gpeek.spawnmenu.daddonbrowser.tooltip=Разглеждане на вътрешните механизми

gpeek.extensions.error.message=Типът файл не се поддържа в момента.

gpeek.extensions.lua.empty=Този файл е празен
gpeek.extensions.lua.copy=Копиране на съдържанието на файла

gpeek.extensions.mdl.animations.placeholder=изберете анимация...
gpeek.extensions.mdl.skin=Скин
gpeek.extensions.mdl.invert=Инвертиране на фона

gpeek.extensions.pcf.message=Нуждаете се от 'Particle Effects+' (3684885115), за да видите този файл.
gpeek.extensions.pcf.workshop=Вижте в Workshop

gpeek.extensions.ttf.fontscale=Мащаб на шрифта
gpeek.extensions.ttf.error=Шрифтът не можа да бъде зареден.
gpeek.extensions.ttf.copy=Копиране на името на шрифта

gpeek.extensions.vmt.texture=Текстура
gpeek.extensions.vmt.scale=Мащаб
gpeek.extensions.vmt.invert=Инвертиране на фона
gpeek.extensions.vmt.material=Материал

gpeek.extensions.wav.stop=Спри
gpeek.settings=Настройки на gPeek
gpeek.settings.multiaddon=Преглед на множество добавки
gpeek.settings.multiaddon.help=\nПозволява преглед на множество добавки едновременно. Отварянето на много добавки може да причини забавяне.
gpeek.settings.batchsize=Размер на партидата файлове
gpeek.settings.batchsize.help=\nБрой файлове за обработка на партида при преглед на добавка.
gpeek.settings.batchdelay=Закъснение на партидата файлове
gpeek.settings.batchdelay.help=\nВреме между всяка партида файлове при преглед на добавка.
gpeek.settings.blacklist=Черен списък на файлове
gpeek.settings.legacyaddon=Покажи стари добавки
gpeek.settings.legacyaddon.help=\nЗареждане на стари добавки от диска. Експериментално.