
gpeek.spawnmenu.daddonbrowser.tooltip=Naršyti vidines mechanizmas

gpeek.extensions.error.message=Šis failo tipas šiuo metu nepalaikomas.

gpeek.extensions.lua.empty=Šis failas yra tuščias
gpeek.extensions.lua.copy=Kopijuoti failo turinį

gpeek.extensions.mdl.animations.placeholder=pasirinkite animaciją...
gpeek.extensions.mdl.skin=Oda
gpeek.extensions.mdl.invert=Apversti foną

gpeek.extensions.pcf.message=Norėdami peržiūrėti šį failą, jums reikia 'Particle Effects+' (3684885115).
gpeek.extensions.pcf.workshop=Žiūrėti Workshop

gpeek.extensions.ttf.fontscale=Šrifto dydis
gpeek.extensions.ttf.error=Nepavyko įkelti šrifto.
gpeek.extensions.ttf.copy=Kopijuoti šrifto pavadinimą

gpeek.extensions.vmt.texture=Tekstūra
gpeek.extensions.vmt.scale=Mastelis
gpeek.extensions.vmt.invert=Apversti foną
gpeek.extensions.vmt.material=Medžiaga

gpeek.extensions.wav.stop=Sustabdyti
gpeek.settings=gPeek nustatymai
gpeek.settings.multiaddon=Kelių priedų naršymas
gpeek.settings.multiaddon.help=\nLeisti naršyti kelis priedus vienu metu. Atidarius daug priedų gali atsirasti vėlavimas.
gpeek.settings.batchsize=Failų paketo dydis
gpeek.settings.batchsize.help=\nFailų skaičius, apdorojamas per paketą naršant priedą.
gpeek.settings.batchdelay=Failų paketo uždelsimas
gpeek.settings.batchdelay.help=\nLaikas tarp kiekvieno failų paketo naršant priedą.
gpeek.settings.blacklist=Failų juodasis sąrašas
gpeek.settings.legacyaddon=Rodyti senuosius priedus
gpeek.settings.legacyaddon.help=\nĮkelti senuosius priedus iš disko. Eksperimentinė funkcija.