
gpeek.spawnmenu.daddonbrowser.tooltip=İç mekanizmalara göz atılıyor

gpeek.extensions.error.message=Dosya türü şu anda desteklenmiyor.

gpeek.extensions.lua.empty=Bu dosya boş
gpeek.extensions.lua.copy=Dosya içeriğini kopyala

gpeek.extensions.mdl.animations.placeholder=animasyon seç...
gpeek.extensions.mdl.skin=Görünüm
gpeek.extensions.mdl.invert=Arka planı ters çevir

gpeek.extensions.pcf.message=Bu dosyayı görüntülemek için 'Particle Effects+' (3684885115) gereklidir.
gpeek.extensions.pcf.workshop=Atölyede gör

gpeek.extensions.ttf.fontscale=Yazı Tipi Boyutu
gpeek.extensions.ttf.error=Yazı tipi yüklenemedi.
gpeek.extensions.ttf.copy=Yazı tipi adını kopyala

gpeek.extensions.vmt.texture=Doku
gpeek.extensions.vmt.scale=Ölçek
gpeek.extensions.vmt.invert=Arka planı ters çevir
gpeek.extensions.vmt.material=Malzeme

gpeek.extensions.wav.stop=Durdur
gpeek.settings=gPeek Ayarları
gpeek.settings.multiaddon=Çoklu Eklenti Gezinme
gpeek.settings.multiaddon.help=\nAynı anda birden fazla eklentiye göz atmaya izin ver. Çok fazla eklenti açmak gecikmeye neden olabilir.
gpeek.settings.batchsize=Dosya Yığın Boyutu
gpeek.settings.batchsize.help=\nEklentiye göz atarken her yığında işlenecek dosya sayısı.
gpeek.settings.batchdelay=Dosya Yığın Gecikmesi
gpeek.settings.batchdelay.help=\nEklentiye göz atarken her dosya yığını arasındaki süre.
gpeek.settings.blacklist=Dosya Kara Listesi
gpeek.settings.legacyaddon=Eski Eklentileri Göster
gpeek.settings.legacyaddon.help=\nEski eklentileri diskten yükle. (Deneysel)
