
gpeek.spawnmenu.daddonbrowser.tooltip=İç mekanizmalara göz atılıyor

gpeek.extensions.error.message=Dosya türü şu anda desteklenmiyor.

gpeek.extensions.lua.empty=Bu dosya boş
gpeek.extensions.lua.copy=Dosya içeriğini kopyala

gpeek.extensions.mdl.animations.placeholder=animasyon seç...
gpeek.extensions.mdl.skin=Deri
gpeek.extensions.mdl.invert=Arka planı ters çevir

gpeek.extensions.pcf.message=Bu dosyayı görüntülemek için 'Particle Effects+' (3684885115) gereklidir.
gpeek.extensions.pcf.workshop=Workshop'ta gör

gpeek.extensions.ttf.fontscale=Yazı Tipi Boyutu
gpeek.extensions.ttf.error=Yazı tipi yüklenemedi.
gpeek.extensions.ttf.copy=Yazı tipi adını kopyala

gpeek.extensions.vmt.texture=Doku
gpeek.extensions.vmt.scale=Ölçek
gpeek.extensions.vmt.invert=Arka planı ters çevir
gpeek.extensions.vmt.material=Malzeme

gpeek.extensions.wav.stop=Durdur