
gpeek.spawnmenu.daddonbrowser.tooltip=Gennemser de indre mekanismer

gpeek.extensions.error.message=Filtypen understøttes ikke i øjeblikket.

gpeek.extensions.lua.empty=Denne fil er tom
gpeek.extensions.lua.copy=Kopier filindhold

gpeek.extensions.mdl.animations.placeholder=vælg animation...
gpeek.extensions.mdl.skin=Skin
gpeek.extensions.mdl.invert=Inverter baggrund

gpeek.extensions.pcf.message=Du har brug for 'Particle Effects+' (3684885115) for at se denne fil.
gpeek.extensions.pcf.workshop=Se i Workshop

gpeek.extensions.ttf.fontscale=Skriftstørrelse
gpeek.extensions.ttf.error=Kunne ikke indlæse skrifttype.
gpeek.extensions.ttf.copy=Kopier skrifttypens navn

gpeek.extensions.vmt.texture=Tekstur
gpeek.extensions.vmt.scale=Skala
gpeek.extensions.vmt.invert=Inverter baggrund
gpeek.extensions.vmt.material=Materiale

gpeek.extensions.wav.stop=Stop
gpeek.settings=gPeek indstillinger
gpeek.settings.multiaddon=Gennemse flere tilføjelser
gpeek.settings.multiaddon.help=\nTillad gennemse af flere tilføjelser på samme tid. Åbning af mange tilføjelser kan forårsage forsinkelse.
gpeek.settings.batchsize=Filbatchstørrelse
gpeek.settings.batchsize.help=\nAntal filer der behandles pr. batch ved gennemse af en tilføjelse.
gpeek.settings.batchdelay=Filbatchforsinkelse
gpeek.settings.batchdelay.help=\nTid mellem hver filbatch ved gennemse af en tilføjelse.
gpeek.settings.blacklist=Fil-sortliste
gpeek.settings.legacyaddon=Vis ældre tilføjelser
gpeek.settings.legacyaddon.help=\nIndlæs ældre tilføjelser fra disk. Eksperimentel.