
gpeek.spawnmenu.daddonbrowser.tooltip=A belső mechanizmusok böngészése

gpeek.extensions.error.message=A fájltípus jelenleg nem támogatott.

gpeek.extensions.lua.empty=Ez a fájl üres
gpeek.extensions.lua.copy=Fájl tartalmának másolása

gpeek.extensions.mdl.animations.placeholder=animáció kiválasztása...
gpeek.extensions.mdl.skin=Skin
gpeek.extensions.mdl.invert=Háttér invertálása

gpeek.extensions.pcf.message=A fájl megtekintéséhez szükséged van a 'Particle Effects+' (3684885115) kiegészítőre.
gpeek.extensions.pcf.workshop=Megtekintés a Workshopban

gpeek.extensions.ttf.fontscale=Betűméret
gpeek.extensions.ttf.error=Nem sikerült betölteni a betűtípust.
gpeek.extensions.ttf.copy=Betűtípus nevének másolása

gpeek.extensions.vmt.texture=Textúra
gpeek.extensions.vmt.scale=Méretarány
gpeek.extensions.vmt.invert=Háttér invertálása
gpeek.extensions.vmt.material=Anyag

gpeek.extensions.wav.stop=Megállítás
gpeek.settings=gPeek beállítások
gpeek.settings.multiaddon=Több kiegészítő böngészése
gpeek.settings.multiaddon.help=\nLehetővé teszi több kiegészítő egyidejű böngészését. Sok kiegészítő megnyitása késést okozhat.
gpeek.settings.batchsize=Fájl köteg mérete
gpeek.settings.batchsize.help=\nEgy kötegben feldolgozandó fájlok száma egy kiegészítő böngészésekor.
gpeek.settings.batchdelay=Fájl köteg késleltetése
gpeek.settings.batchdelay.help=\nAz egyes fájl kötegek közötti idő egy kiegészítő böngészésekor.
gpeek.settings.blacklist=Fájl fekete lista
gpeek.settings.legacyaddon=Régi kiegészítők megjelenítése
gpeek.settings.legacyaddon.help=\nRégi kiegészítők betöltése lemezről. Kísérleti.