
gpeek.spawnmenu.daddonbrowser.tooltip=Przeglądanie wewnętrznych mechanizmów

gpeek.extensions.error.message=Typ pliku nie jest aktualnie obsługiwany.

gpeek.extensions.lua.empty=Ten plik jest pusty
gpeek.extensions.lua.copy=Kopiuj zawartość pliku

gpeek.extensions.mdl.animations.placeholder=wybierz animację...
gpeek.extensions.mdl.skin=Skin
gpeek.extensions.mdl.invert=Odwróć tło

gpeek.extensions.pcf.message=Potrzebujesz 'Particle Effects+' (3684885115), aby wyświetlić ten plik.
gpeek.extensions.pcf.workshop=Zobacz w Workshop

gpeek.extensions.ttf.fontscale=Rozmiar czcionki
gpeek.extensions.ttf.error=Nie można załadować czcionki.
gpeek.extensions.ttf.copy=Kopiuj nazwę czcionki

gpeek.extensions.vmt.texture=Tekstura
gpeek.extensions.vmt.scale=Skala
gpeek.extensions.vmt.invert=Odwróć tło
gpeek.extensions.vmt.material=Materiał

gpeek.extensions.wav.stop=Zatrzymaj
gpeek.settings=Ustawienia gPeek
gpeek.settings.multiaddon=Przeglądanie wielu dodatków
gpeek.settings.multiaddon.help=\nUmożliwia jednoczesne przeglądanie wielu dodatków. Otwieranie wielu dodatków może powodować spowolnienie.
gpeek.settings.batchsize=Rozmiar partii plików
gpeek.settings.batchsize.help=\nLiczba plików przetwarzanych na partię podczas przeglądania dodatku.
gpeek.settings.batchdelay=Opóźnienie partii plików
gpeek.settings.batchdelay.help=\nCzas między każdą partią plików podczas przeglądania dodatku.
gpeek.settings.blacklist=Czarna lista plików
gpeek.settings.legacyaddon=Pokaż starsze dodatki
gpeek.settings.legacyaddon.help=\nWczytaj starsze dodatki z dysku. Eksperymentalne.