
gpeek.spawnmenu.daddonbrowser.tooltip=Sisäisten mekanismien selaaminen

gpeek.extensions.error.message=Tiedostotyyppiä ei tällä hetkellä tueta.

gpeek.extensions.lua.empty=Tämä tiedosto on tyhjä
gpeek.extensions.lua.copy=Kopioi tiedoston sisältö

gpeek.extensions.mdl.animations.placeholder=valitse animaatio...
gpeek.extensions.mdl.skin=Iho
gpeek.extensions.mdl.invert=Käännä tausta

gpeek.extensions.pcf.message=Tarvitset 'Particle Effects+' (3684885115) tiedoston katseluun.
gpeek.extensions.pcf.workshop=Katso Workshopissa

gpeek.extensions.ttf.fontscale=Fonttikoko
gpeek.extensions.ttf.error=Fonttia ei voitu ladata.
gpeek.extensions.ttf.copy=Kopioi fontin nimi

gpeek.extensions.vmt.texture=Tekstuuri
gpeek.extensions.vmt.scale=Mittakaava
gpeek.extensions.vmt.invert=Käännä tausta
gpeek.extensions.vmt.material=Materiaali

gpeek.extensions.wav.stop=Pysäytä