
gpeek.spawnmenu.daddonbrowser.tooltip=Sisäisten mekanismien selaaminen

gpeek.extensions.error.message=Tiedostotyyppiä ei tällä hetkellä tueta.

gpeek.extensions.lua.empty=Tämä tiedosto on tyhjä
gpeek.extensions.lua.copy=Kopioi tiedoston sisältö

gpeek.extensions.mdl.animations.placeholder=valitse animaatio...
gpeek.extensions.mdl.skin=Iho
gpeek.extensions.mdl.invert=Käännä tausta

gpeek.extensions.pcf.message=Tarvitset 'Particle Effects+' (3684885115) tiedoston katseluun.
gpeek.extensions.pcf.workshop=Katso Workshopissa

gpeek.extensions.ttf.fontscale=Fonttikoko
gpeek.extensions.ttf.error=Fonttia ei voitu ladata.
gpeek.extensions.ttf.copy=Kopioi fontin nimi

gpeek.extensions.vmt.texture=Tekstuuri
gpeek.extensions.vmt.scale=Mittakaava
gpeek.extensions.vmt.invert=Käännä tausta
gpeek.extensions.vmt.material=Materiaali

gpeek.extensions.wav.stop=Pysäytä
gpeek.settings=gPeek asetukset
gpeek.settings.multiaddon=Useiden lisäosien selaaminen
gpeek.settings.multiaddon.help=\nSalli useiden lisäosien samanaikainen selaaminen. Monien lisäosien avaaminen voi aiheuttaa viivettä.
gpeek.settings.batchsize=Tiedoston eräkoko
gpeek.settings.batchsize.help=\nKäsiteltävien tiedostojen määrä erää kohden lisäosaa selatessa.
gpeek.settings.batchdelay=Tiedoston eräviive
gpeek.settings.batchdelay.help=\nAika tiedostoerien välillä lisäosaa selatessa.
gpeek.settings.blacklist=Tiedoston musta lista