
gpeek.spawnmenu.daddonbrowser.tooltip=Pregledavanje unutarnjih mehanizama

gpeek.extensions.error.message=Vrsta datoteke trenutno nije podržana.

gpeek.extensions.lua.empty=Ova datoteka je prazna
gpeek.extensions.lua.copy=Kopiraj sadržaj datoteke

gpeek.extensions.mdl.animations.placeholder=odaberi animaciju...
gpeek.extensions.mdl.skin=Skin
gpeek.extensions.mdl.invert=Invertira pozadinu

gpeek.extensions.pcf.message=Potreban vam je 'Particle Effects+' (3684885115) za prikaz ove datoteke.
gpeek.extensions.pcf.workshop=Pogledaj u Workshopu

gpeek.extensions.ttf.fontscale=Veličina fonta
gpeek.extensions.ttf.error=Font se nije mogao učitati.
gpeek.extensions.ttf.copy=Kopiraj naziv fonta

gpeek.extensions.vmt.texture=Tekstura
gpeek.extensions.vmt.scale=Mjerilo
gpeek.extensions.vmt.invert=Invertira pozadinu
gpeek.extensions.vmt.material=Materijal

gpeek.extensions.wav.stop=Zaustavi
gpeek.settings=gPeek postavke
gpeek.settings.multiaddon=Pregledavanje više dodataka
gpeek.settings.multiaddon.help=\nOmogućuje istovremeno pregledavanje više dodataka. Otvaranje mnogih dodataka može uzrokovati usporavanje.
gpeek.settings.batchsize=Veličina serije datoteka
gpeek.settings.batchsize.help=\nBroj datoteka za obradu po seriji pri pregledavanju dodatka.
gpeek.settings.batchdelay=Kašnjenje serije datoteka
gpeek.settings.batchdelay.help=\nVrijeme između svake serije datoteka pri pregledavanju dodatka.
gpeek.settings.blacklist=Crna lista datoteka