
gpeek.spawnmenu.daddonbrowser.tooltip=正在浏览内部机制

gpeek.extensions.error.message=当前不支持该文件类型。

gpeek.extensions.lua.empty=此文件为空
gpeek.extensions.lua.copy=复制文件内容

gpeek.extensions.mdl.animations.placeholder=选择动画...
gpeek.extensions.mdl.skin=皮肤
gpeek.extensions.mdl.invert=反转背景

gpeek.extensions.pcf.message=您需要安装 'Particle Effects+' (3684885115) 才能查看此文件。
gpeek.extensions.pcf.workshop=在创意工坊中查看

gpeek.extensions.ttf.fontscale=字体大小
gpeek.extensions.ttf.error=无法加载字体。
gpeek.extensions.ttf.copy=复制字体名称

gpeek.extensions.vmt.texture=纹理
gpeek.extensions.vmt.scale=缩放
gpeek.extensions.vmt.invert=反转背景
gpeek.extensions.vmt.material=材质

gpeek.extensions.wav.stop=停止