
gpeek.spawnmenu.daddonbrowser.tooltip=내부 메커니즘 탐색 중

gpeek.extensions.error.message=현재 지원되지 않는 파일 형식입니다.

gpeek.extensions.lua.empty=이 파일은 비어 있습니다
gpeek.extensions.lua.copy=파일 내용 복사

gpeek.extensions.mdl.animations.placeholder=애니메이션 선택...
gpeek.extensions.mdl.skin=스킨
gpeek.extensions.mdl.invert=배경 반전

gpeek.extensions.pcf.message=이 파일을 보려면 'Particle Effects+' (3684885115)가 필요합니다.
gpeek.extensions.pcf.workshop=Workshop에서 보기

gpeek.extensions.ttf.fontscale=글꼴 크기
gpeek.extensions.ttf.error=글꼴을 불러올 수 없습니다.
gpeek.extensions.ttf.copy=글꼴 이름 복사

gpeek.extensions.vmt.texture=텍스처
gpeek.extensions.vmt.scale=스케일
gpeek.extensions.vmt.invert=배경 반전
gpeek.extensions.vmt.material=재질

gpeek.extensions.wav.stop=정지
gpeek.settings=gPeek 설정
gpeek.settings.multiaddon=멀티 애드온 탐색
gpeek.settings.multiaddon.help=\n여러 애드온을 동시에 탐색할 수 있습니다. 많은 애드온을 열면 렉이 발생할 수 있습니다.
gpeek.settings.batchsize=파일 배치 크기
gpeek.settings.batchsize.help=\n애드온 탐색 시 배치당 처리할 파일 수.
gpeek.settings.batchdelay=파일 배치 지연
gpeek.settings.batchdelay.help=\n애드온 탐색 시 각 파일 배치 사이의 시간.
gpeek.settings.blacklist=파일 블랙리스트
gpeek.settings.legacyaddon=레거시 애드온 표시
gpeek.settings.legacyaddon.help=\n디스크에서 레거시 애드온을 불러옵니다. 실험적 기능.