
gpeek.spawnmenu.daddonbrowser.tooltip=กำลังเรียกดูกลไกภายใน

gpeek.extensions.error.message=ประเภทไฟล์นี้ยังไม่รองรับในขณะนี้

gpeek.extensions.lua.empty=ไฟล์นี้ว่างเปล่า
gpeek.extensions.lua.copy=คัดลอกเนื้อหาไฟล์

gpeek.extensions.mdl.animations.placeholder=เลือกภาพเคลื่อนไหว...
gpeek.extensions.mdl.skin=สกิน
gpeek.extensions.mdl.invert=กลับสีพื้นหลัง

gpeek.extensions.pcf.message=คุณต้องมี 'Particle Effects+' (3684885115) เพื่อดูไฟล์นี้
gpeek.extensions.pcf.workshop=ดูใน Workshop

gpeek.extensions.ttf.fontscale=ขนาดตัวอักษร
gpeek.extensions.ttf.error=ไม่สามารถโหลดแบบอักษรได้
gpeek.extensions.ttf.copy=คัดลอกชื่อแบบอักษร

gpeek.extensions.vmt.texture=พื้นผิว
gpeek.extensions.vmt.scale=มาตราส่วน
gpeek.extensions.vmt.invert=กลับสีพื้นหลัง
gpeek.extensions.vmt.material=วัสดุ

gpeek.extensions.wav.stop=หยุด
gpeek.settings=การตั้งค่า gPeek
gpeek.settings.multiaddon=เรียกดูหลายแอดออน
gpeek.settings.multiaddon.help=\nอนุญาตให้เรียกดูหลายแอดออนพร้อมกัน การเปิดแอดออนจำนวนมากอาจทำให้เกิดความล่าช้า
gpeek.settings.batchsize=ขนาดชุดไฟล์
gpeek.settings.batchsize.help=\nจำนวนไฟล์ที่ประมวลผลต่อชุดขณะเรียกดูแอดออน
gpeek.settings.batchdelay=ความล่าช้าชุดไฟล์
gpeek.settings.batchdelay.help=\nเวลาระหว่างแต่ละชุดไฟล์ขณะเรียกดูแอดออน
gpeek.settings.blacklist=บัญชีดำไฟล์
gpeek.settings.legacyaddon=แสดงแอดออนเดิม
gpeek.settings.legacyaddon.help=\nโหลดแอดออนเดิมจากดิสก์ ทดลองใช้งาน