
gpeek.spawnmenu.daddonbrowser.tooltip=Explorando los mecanismos internos

gpeek.extensions.error.message=Tipo de archivo no compatible actualmente.

gpeek.extensions.lua.empty=Este archivo está vacío
gpeek.extensions.lua.copy=Copiar contenido del archivo

gpeek.extensions.mdl.animations.placeholder=seleccionar animación...
gpeek.extensions.mdl.skin=Skin
gpeek.extensions.mdl.invert=Invertir fondo

gpeek.extensions.pcf.message=Necesitas 'Particle Effects+' (3684885115) para ver este archivo.
gpeek.extensions.pcf.workshop=Ver en el Workshop

gpeek.extensions.ttf.fontscale=Escala de fuente
gpeek.extensions.ttf.error=No se pudo cargar la fuente.
gpeek.extensions.ttf.copy=Copiar nombre de fuente

gpeek.extensions.vmt.texture=Textura
gpeek.extensions.vmt.scale=Escala
gpeek.extensions.vmt.invert=Invertir fondo
gpeek.extensions.vmt.material=Material

gpeek.extensions.wav.stop=Detener