
gpeek.spawnmenu.daddonbrowser.tooltip=Durchsuchen der internen Mechanismen

gpeek.extensions.error.message=Dateityp wird derzeit nicht unterstützt.

gpeek.extensions.lua.empty=Diese Datei ist leer
gpeek.extensions.lua.copy=Dateiinhalt kopieren

gpeek.extensions.mdl.animations.placeholder=Animation auswählen...
gpeek.extensions.mdl.skin=Skin
gpeek.extensions.mdl.invert=Hintergrund invertieren

gpeek.extensions.pcf.message=Sie benötigen 'Particle Effects+' (3684885115), um diese Datei anzuzeigen.
gpeek.extensions.pcf.workshop=Im Workshop ansehen

gpeek.extensions.ttf.fontscale=Schriftgröße
gpeek.extensions.ttf.error=Schriftart konnte nicht geladen werden.
gpeek.extensions.ttf.copy=Schriftartname kopieren

gpeek.extensions.vmt.texture=Textur
gpeek.extensions.vmt.scale=Skalierung
gpeek.extensions.vmt.invert=Hintergrund invertieren
gpeek.extensions.vmt.material=Material

gpeek.extensions.wav.stop=Stop