
gpeek.spawnmenu.daddonbrowser.tooltip=Перегляд внутрішніх механізмів

gpeek.extensions.error.message=Тип файлу наразі не підтримується.

gpeek.extensions.lua.empty=Цей файл порожній
gpeek.extensions.lua.copy=Копіювати вміст файлу

gpeek.extensions.mdl.animations.placeholder=виберіть анімацію...
gpeek.extensions.mdl.skin=Скін
gpeek.extensions.mdl.invert=Інвертувати фон

gpeek.extensions.pcf.message=Для перегляду цього файлу потрібен 'Particle Effects+' (3684885115).
gpeek.extensions.pcf.workshop=Переглянути у Workshop

gpeek.extensions.ttf.fontscale=Розмір шрифту
gpeek.extensions.ttf.error=Не вдалося завантажити шрифт.
gpeek.extensions.ttf.copy=Копіювати назву шрифту

gpeek.extensions.vmt.texture=Текстура
gpeek.extensions.vmt.scale=Масштаб
gpeek.extensions.vmt.invert=Інвертувати фон
gpeek.extensions.vmt.material=Матеріал

gpeek.extensions.wav.stop=Зупинити