
gpeek.spawnmenu.daddonbrowser.tooltip=A navegar pelos mecanismos internos

gpeek.extensions.error.message=Tipo de ficheiro não suportado de momento.

gpeek.extensions.lua.empty=Este ficheiro está vazio
gpeek.extensions.lua.copy=Copiar conteúdo do ficheiro

gpeek.extensions.mdl.animations.placeholder=selecionar animação...
gpeek.extensions.mdl.skin=Skin
gpeek.extensions.mdl.invert=Inverter fundo

gpeek.extensions.pcf.message=Precisa de 'Particle Effects+' (3684885115) para ver este ficheiro.
gpeek.extensions.pcf.workshop=Ver na Workshop

gpeek.extensions.ttf.fontscale=Tamanho da fonte
gpeek.extensions.ttf.error=Não foi possível carregar a fonte.
gpeek.extensions.ttf.copy=Copiar nome da fonte

gpeek.extensions.vmt.texture=Textura
gpeek.extensions.vmt.scale=Escala
gpeek.extensions.vmt.invert=Inverter fundo
gpeek.extensions.vmt.material=Material

gpeek.extensions.wav.stop=Parar
gpeek.settings=Definições do gPeek
gpeek.settings.multiaddon=Navegação multi-addon
gpeek.settings.multiaddon.help=\nPermite navegar por vários addons ao mesmo tempo. Abrir muitos addons pode causar atrasos.
gpeek.settings.batchsize=Tamanho do lote de ficheiros
gpeek.settings.batchsize.help=\nNúmero de ficheiros a processar por lote ao navegar num addon.
gpeek.settings.batchdelay=Atraso do lote de ficheiros
gpeek.settings.batchdelay.help=\nTempo entre cada lote de ficheiros ao navegar num addon.
gpeek.settings.blacklist=Lista negra de ficheiros