
gpeek.spawnmenu.daddonbrowser.tooltip=Door de interne mechanismen bladeren

gpeek.extensions.error.message=Bestandstype wordt momenteel niet ondersteund.

gpeek.extensions.lua.empty=Dit bestand is leeg
gpeek.extensions.lua.copy=Bestandsinhoud kopiëren

gpeek.extensions.mdl.animations.placeholder=animatie selecteren...
gpeek.extensions.mdl.skin=Skin
gpeek.extensions.mdl.invert=Achtergrond omkeren

gpeek.extensions.pcf.message=Je hebt 'Particle Effects+' (3684885115) nodig om dit bestand te bekijken.
gpeek.extensions.pcf.workshop=Bekijk in Workshop

gpeek.extensions.ttf.fontscale=Lettergrootte
gpeek.extensions.ttf.error=Lettertype kon niet worden geladen.
gpeek.extensions.ttf.copy=Lettertypenaam kopiëren

gpeek.extensions.vmt.texture=Textuur
gpeek.extensions.vmt.scale=Schaal
gpeek.extensions.vmt.invert=Achtergrond omkeren
gpeek.extensions.vmt.material=Materiaal

gpeek.extensions.wav.stop=Stoppen
gpeek.settings=gPeek instellingen
gpeek.settings.multiaddon=Meerdere add-ons doorbladeren
gpeek.settings.multiaddon.help=\nStaat het gelijktijdig doorbladeren van meerdere add-ons toe. Het openen van veel add-ons kan vertraging veroorzaken.
gpeek.settings.batchsize=Bestandsbatch-grootte
gpeek.settings.batchsize.help=\nAantal bestanden dat per batch wordt verwerkt bij het doorbladeren van een add-on.
gpeek.settings.batchdelay=Bestandsbatch-vertraging
gpeek.settings.batchdelay.help=\nTijd tussen elke bestandsbatch bij het doorbladeren van een add-on.
gpeek.settings.blacklist=Bestandsblacklist