
gpeek.spawnmenu.daddonbrowser.tooltip=Door de interne mechanismen bladeren

gpeek.extensions.error.message=Bestandstype wordt momenteel niet ondersteund.

gpeek.extensions.lua.empty=Dit bestand is leeg
gpeek.extensions.lua.copy=Bestandsinhoud kopiëren

gpeek.extensions.mdl.animations.placeholder=animatie selecteren...
gpeek.extensions.mdl.skin=Skin
gpeek.extensions.mdl.invert=Achtergrond omkeren

gpeek.extensions.pcf.message=Je hebt 'Particle Effects+' (3684885115) nodig om dit bestand te bekijken.
gpeek.extensions.pcf.workshop=Bekijk in Workshop

gpeek.extensions.ttf.fontscale=Lettergrootte
gpeek.extensions.ttf.error=Lettertype kon niet worden geladen.
gpeek.extensions.ttf.copy=Lettertypenaam kopiëren

gpeek.extensions.vmt.texture=Textuur
gpeek.extensions.vmt.scale=Schaal
gpeek.extensions.vmt.invert=Achtergrond omkeren
gpeek.extensions.vmt.material=Materiaal

gpeek.extensions.wav.stop=Stoppen