
gpeek.spawnmenu.daddonbrowser.tooltip=正在瀏覽內部機制

gpeek.extensions.error.message=目前不支援此檔案類型。

gpeek.extensions.lua.empty=此檔案為空
gpeek.extensions.lua.copy=複製檔案內容

gpeek.extensions.mdl.animations.placeholder=選擇動畫...
gpeek.extensions.mdl.skin=皮膚
gpeek.extensions.mdl.invert=反轉背景

gpeek.extensions.pcf.message=您需要安裝 'Particle Effects+' (3684885115) 才能檢視此檔案。
gpeek.extensions.pcf.workshop=在創意工坊中查看

gpeek.extensions.ttf.fontscale=字體大小
gpeek.extensions.ttf.error=無法載入字體。
gpeek.extensions.ttf.copy=複製字體名稱

gpeek.extensions.vmt.texture=紋理
gpeek.extensions.vmt.scale=縮放
gpeek.extensions.vmt.invert=反轉背景
gpeek.extensions.vmt.material=材質

gpeek.extensions.wav.stop=停止