
gpeek.spawnmenu.daddonbrowser.tooltip=Explorando los mecanismos internos

gpeek.extensions.error.message=Tipo de archivo no compatible actualmente.

gpeek.extensions.lua.empty=Este archivo está vacío
gpeek.extensions.lua.copy=Copiar contenido del archivo

gpeek.extensions.mdl.animations.placeholder=seleccionar animación...
gpeek.extensions.mdl.skin=Skin
gpeek.extensions.mdl.invert=Invertir fondo

gpeek.extensions.pcf.message=Necesitas 'Particle Effects+' (3684885115) para ver este archivo.
gpeek.extensions.pcf.workshop=Ver en el Workshop

gpeek.extensions.ttf.fontscale=Escala de fuente
gpeek.extensions.ttf.error=No se pudo cargar la fuente.
gpeek.extensions.ttf.copy=Copiar nombre de fuente

gpeek.extensions.vmt.texture=Textura
gpeek.extensions.vmt.scale=Escala
gpeek.extensions.vmt.invert=Invertir fondo
gpeek.extensions.vmt.material=Material

gpeek.extensions.wav.stop=Detener
gpeek.settings=Configuración de gPeek
gpeek.settings.multiaddon=Explorar múltiples complementos
gpeek.settings.multiaddon.help=\nPermite explorar varios complementos al mismo tiempo. Abrir muchos complementos puede causar retrasos.
gpeek.settings.batchsize=Tamaño de lote de archivos
gpeek.settings.batchsize.help=\nNúmero de archivos a procesar por lote al explorar un complemento.
gpeek.settings.batchdelay=Retraso de lote de archivos
gpeek.settings.batchdelay.help=\nTiempo entre cada lote de archivos al explorar un complemento.
gpeek.settings.blacklist=Lista negra de archivos
gpeek.settings.legacyaddon=Mostrar complementos heredados
gpeek.settings.legacyaddon.help=\nCargar complementos heredados desde el disco. Experimental.