
gpeek.spawnmenu.daddonbrowser.tooltip=Просмотр внутренних механизмов

gpeek.extensions.error.message=Тип файла в данный момент не поддерживается.

gpeek.extensions.lua.empty=Этот файл пуст
gpeek.extensions.lua.copy=Скопировать содержимое файла

gpeek.extensions.mdl.animations.placeholder=выберите анимацию...
gpeek.extensions.mdl.skin=Скин
gpeek.extensions.mdl.invert=Инвертировать фон

gpeek.extensions.pcf.message=Для просмотра этого файла необходим 'Particle Effects+' (3684885115).
gpeek.extensions.pcf.workshop=Смотреть в Workshop

gpeek.extensions.ttf.fontscale=Размер шрифта
gpeek.extensions.ttf.error=Не удалось загрузить шрифт.
gpeek.extensions.ttf.copy=Скопировать название шрифта

gpeek.extensions.vmt.texture=Текстура
gpeek.extensions.vmt.scale=Масштаб
gpeek.extensions.vmt.invert=Инвертировать фон
gpeek.extensions.vmt.material=Материал

gpeek.extensions.wav.stop=Остановить
gpeek.settings=Настройки gPeek
gpeek.settings.multiaddon=Просмотр нескольких аддонов
gpeek.settings.multiaddon.help=\nРазрешить одновременный просмотр нескольких аддонов. Открытие большого количества аддонов может вызвать задержки.
gpeek.settings.batchsize=Размер пакета файлов
gpeek.settings.batchsize.help=\nКоличество файлов для обработки за один пакет при просмотре аддона.
gpeek.settings.batchdelay=Задержка пакета файлов
gpeek.settings.batchdelay.help=\nВремя между каждым пакетом файлов при просмотре аддона.
gpeek.settings.blacklist=Чёрный список файлов
gpeek.settings.legacyaddon=Показать устаревшие аддоны
gpeek.settings.legacyaddon.help=\nЗагрузить устаревшие аддоны с диска. Экспериментально.