
gpeek.spawnmenu.daddonbrowser.tooltip=Browsing the inner machinations

gpeek.extensions.error.message=Filetype not currently supported.

gpeek.extensions.lua.empty=This file is empty
gpeek.extensions.lua.copy=Copy file contents

gpeek.extensions.mdl.animations.placeholder=select animation...
gpeek.extensions.mdl.skin=Skin
gpeek.extensions.mdl.invert=Invert background

gpeek.extensions.pcf.message=You need 'Particle Effects+' (3684885115) to view this file.
gpeek.extensions.pcf.workshop=See in Workshop

gpeek.extensions.ttf.fontscale=Font Scale
gpeek.extensions.ttf.error=Could not load font.
gpeek.extensions.ttf.copy=Copy font name

gpeek.extensions.vmt.texture=Texture
gpeek.extensions.vmt.scale=Scale
gpeek.extensions.vmt.invert=Invert background
gpeek.extensions.vmt.material=Material

gpeek.extensions.wav.stop=Stop
gpeek.settings=gPeek Settings
gpeek.settings.multiaddon=Multi-Addon Browse
gpeek.settings.multiaddon.help=\nAllow browsing multiple addons at the same time. Opening a lot of addons may cause lag.
gpeek.settings.batchsize=File Batch Size
gpeek.settings.batchsize.help=\nNumber of files to process per batch when browsing an addon.
gpeek.settings.batchdelay=File Batch Delay
gpeek.settings.batchdelay.help=\nAmount of time between each file batch when browsing an addon.
gpeek.settings.blacklist=File Blacklist
gpeek.settings.legacyaddon=Show Legacy Addons
gpeek.settings.legacyaddon.help=\nLoad legacy addons from disk. Experimental.