
gpeek.spawnmenu.daddonbrowser.tooltip=Navegando pelos mecanismos internos

gpeek.extensions.error.message=Tipo de arquivo não suportado no momento.

gpeek.extensions.lua.empty=Este arquivo está vazio
gpeek.extensions.lua.copy=Copiar conteúdo do arquivo

gpeek.extensions.mdl.animations.placeholder=selecionar animação...
gpeek.extensions.mdl.skin=Skin
gpeek.extensions.mdl.invert=Inverter fundo

gpeek.extensions.pcf.message=Você precisa do 'Particle Effects+' (3684885115) para ver este arquivo.
gpeek.extensions.pcf.workshop=Ver na Workshop

gpeek.extensions.ttf.fontscale=Tamanho da fonte
gpeek.extensions.ttf.error=Não foi possível carregar a fonte.
gpeek.extensions.ttf.copy=Copiar nome da fonte

gpeek.extensions.vmt.texture=Textura
gpeek.extensions.vmt.scale=Escala
gpeek.extensions.vmt.invert=Inverter fundo
gpeek.extensions.vmt.material=Material

gpeek.extensions.wav.stop=Parar
gpeek.settings=Configurações do gPeek
gpeek.settings.multiaddon=Navegação multi-addon
gpeek.settings.multiaddon.help=\nPermite navegar por vários addons ao mesmo tempo. Abrir muitos addons pode causar travamentos.
gpeek.settings.batchsize=Tamanho do lote de arquivos
gpeek.settings.batchsize.help=\nNúmero de arquivos a processar por lote ao navegar por um addon.
gpeek.settings.batchdelay=Atraso do lote de arquivos
gpeek.settings.batchdelay.help=\nTempo entre cada lote de arquivos ao navegar por um addon.
gpeek.settings.blacklist=Lista negra de arquivos
gpeek.settings.legacyaddon=Mostrar addons legados
gpeek.settings.legacyaddon.help=\nCarregar addons legados do disco. Experimental.