
gpeek.spawnmenu.daddonbrowser.tooltip=Plunderin' the inner machinations, arr!

gpeek.extensions.error.message=Blimey! This filetype be not supported yet, arr!

gpeek.extensions.lua.empty=This here file be empty, arr!
gpeek.extensions.lua.copy=Pillage the file contents, arr!

gpeek.extensions.mdl.animations.placeholder=pick yer animation...
gpeek.extensions.mdl.skin=Skin
gpeek.extensions.mdl.invert=Flip the background, arr!

gpeek.extensions.pcf.message=Ye be needin' 'Particle Effects+' (3684885115) to spy this file, arr!
gpeek.extensions.pcf.workshop=Spy in the Workshop

gpeek.extensions.ttf.fontscale=Font Scale
gpeek.extensions.ttf.error=Blimey! Could not load the font, arr!
gpeek.extensions.ttf.copy=Pilfer the font name

gpeek.extensions.vmt.texture=Texture
gpeek.extensions.vmt.scale=Scale
gpeek.extensions.vmt.invert=Flip the background, arr!
gpeek.extensions.vmt.material=Material

gpeek.extensions.wav.stop=Halt!