
gpeek.spawnmenu.daddonbrowser.tooltip=Navigare nei meccanismi interni

gpeek.extensions.error.message=Tipo di file non supportato al momento.

gpeek.extensions.lua.empty=Questo file è vuoto
gpeek.extensions.lua.copy=Copia il contenuto del file

gpeek.extensions.mdl.animations.placeholder=seleziona animazione...
gpeek.extensions.mdl.skin=Skin
gpeek.extensions.mdl.invert=Inverti sfondo

gpeek.extensions.pcf.message=Hai bisogno di 'Particle Effects+' (3684885115) per visualizzare questo file.
gpeek.extensions.pcf.workshop=Vedi nel Workshop

gpeek.extensions.ttf.fontscale=Scala del carattere
gpeek.extensions.ttf.error=Impossibile caricare il carattere.
gpeek.extensions.ttf.copy=Copia il nome del carattere

gpeek.extensions.vmt.texture=Texture
gpeek.extensions.vmt.scale=Scala
gpeek.extensions.vmt.invert=Inverti sfondo
gpeek.extensions.vmt.material=Materiale

gpeek.extensions.wav.stop=Ferma
gpeek.settings=Impostazioni gPeek
gpeek.settings.multiaddon=Navigazione multi-addon
gpeek.settings.multiaddon.help=\nConsente di navigare in più addon contemporaneamente. L'apertura di molti addon potrebbe causare rallentamenti.
gpeek.settings.batchsize=Dimensione del batch di file
gpeek.settings.batchsize.help=\nNumero di file da elaborare per batch durante la navigazione di un addon.
gpeek.settings.batchdelay=Ritardo del batch di file
gpeek.settings.batchdelay.help=\nTempo tra ogni batch di file durante la navigazione di un addon.
gpeek.settings.blacklist=Lista nera dei file
gpeek.settings.legacyaddon=Mostra addon legacy
gpeek.settings.legacyaddon.help=\nCarica addon legacy dal disco. Sperimentale.