
gpeek.spawnmenu.daddonbrowser.tooltip=Duyệt các cơ chế nội bộ

gpeek.extensions.error.message=Loại tệp hiện không được hỗ trợ.

gpeek.extensions.lua.empty=Tệp này trống
gpeek.extensions.lua.copy=Sao chép nội dung tệp

gpeek.extensions.mdl.animations.placeholder=chọn hoạt ảnh...
gpeek.extensions.mdl.skin=Da
gpeek.extensions.mdl.invert=Đảo ngược nền

gpeek.extensions.pcf.message=Bạn cần 'Particle Effects+' (3684885115) để xem tệp này.
gpeek.extensions.pcf.workshop=Xem trong Workshop

gpeek.extensions.ttf.fontscale=Cỡ chữ
gpeek.extensions.ttf.error=Không thể tải phông chữ.
gpeek.extensions.ttf.copy=Sao chép tên phông chữ

gpeek.extensions.vmt.texture=Kết cấu
gpeek.extensions.vmt.scale=Tỉ lệ
gpeek.extensions.vmt.invert=Đảo ngược nền
gpeek.extensions.vmt.material=Vật liệu

gpeek.extensions.wav.stop=Dừng
gpeek.settings=Cài đặt gPeek
gpeek.settings.multiaddon=Duyệt nhiều addon
gpeek.settings.multiaddon.help=\nCho phép duyệt nhiều addon cùng lúc. Mở quá nhiều addon có thể gây ra độ trễ.
gpeek.settings.batchsize=Kích thước lô tệp
gpeek.settings.batchsize.help=\nSố tệp cần xử lý mỗi lô khi duyệt một addon.
gpeek.settings.batchdelay=Độ trễ lô tệp
gpeek.settings.batchdelay.help=\nThời gian giữa mỗi lô tệp khi duyệt một addon.
gpeek.settings.blacklist=Danh sách đen tệp