
gpeek.spawnmenu.daddonbrowser.tooltip=Parcourir les mécanismes internes

gpeek.extensions.error.message=Type de fichier non pris en charge actuellement.

gpeek.extensions.lua.empty=Ce fichier est vide
gpeek.extensions.lua.copy=Copier le contenu du fichier

gpeek.extensions.mdl.animations.placeholder=sélectionner une animation...
gpeek.extensions.mdl.skin=Skin
gpeek.extensions.mdl.invert=Inverser l'arrière-plan

gpeek.extensions.pcf.message=Vous avez besoin de 'Particle Effects+' (3684885115) pour voir ce fichier.
gpeek.extensions.pcf.workshop=Voir dans le Workshop

gpeek.extensions.ttf.fontscale=Taille de la police
gpeek.extensions.ttf.error=Impossible de charger la police.
gpeek.extensions.ttf.copy=Copier le nom de la police

gpeek.extensions.vmt.texture=Texture
gpeek.extensions.vmt.scale=Échelle
gpeek.extensions.vmt.invert=Inverser l'arrière-plan
gpeek.extensions.vmt.material=Matériau

gpeek.extensions.wav.stop=Arrêter